spring:
  #开发环境
  profiles: dev
  #端口号
  server:
    port: 8081

  #数据源配置
  datasource:
    druid:
      username: root
      password: root
      jdbc-url: jdbc:mysql://106.52.169.187:3306/mine?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2b8
      # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 200
      max-idle: 10
      min-idle: 8
      initial-size: 10
      maxWait: 60000 #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.ico
        session-stat-enable: false
        session-stat-max-count: 10
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username:
        login-password:
        allow:
        deny:
      filter:
        stat:
          enabled: true
          db-type: h2
          log-slow-sql: true

  #redis配置
  redis:
    database: 1
    host: 106.52.169.187
    port: 6379
    password: root
    timeout: 5000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 400
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 10
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 1
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: -1

  #rabbitmq配置，该配置参数与RabbitProperties类中参数对应，springboot的RabbitAutoConfiguration中有自动装配rabbitmq的逻辑
  rabbitmq:
    host: 106.52.169.187
    port: 5672
    virtual-host: tulingvip-springboot-rabbitmq
    username: root
    password: root
    connection-timeout: 5000
    template:
      mandatory: true

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
  mapper-locations: classpath*:/xmlMapper/**/*.xml  指定配置文件的位置